### ISSUE TITLE
Feature request: авторизация по существующим в системе ключам

### ISSUE THREAD

**Issue by davidmz** [DmitryKoterov/dklab_realsync#10]
Сейчас авторизация realsync на удалённом сервере сделана, ИМХО, не очень оптимально:
1. При настройке синхронизации программа требует пароль к удалённому серверу.  Но SSH на сервере может быть настроена на авторизацию только по ключам. В этом случае настроить синхронизацию не удастся.
2. Для каждой новой синхронизируемой директории создаётся новый ключ. В результате на машине разработчика плодится туча ключей, не защищённых паролем, которые неизвестно где лежат и которые дают полный доступ на удалённую машину. Это плохо с т. з. безопасности и неудобно с т. з. управления.

Предложения:
1. Сделать возможность авторизации не по паролю, а по ключу. Пользователь при настройке синхронизации задаёт путь к файлу приватного ключа и в дальнейшем при работе используется _этот_ ключ. Новые записи в authorized_keys не создаются. При необходимости у пользователя запрашивается пароль к ключу.
2. Добавить интеграцию с ssh-agent (*nix) и pageant (Windows). Давать возможность пользователю выбрать нужный ключ из хранящихся в агенте и использовать его для авторизации.

К сожалению, я слишком плохо помню Perl, чтобы написать это самостоятельно…

**Comment by maxttor** [comment]
Я не понял, как это нужно сделать..
Вот у меня есть приватный ключ, созданный vagrant. Как я его могу указать, чтобы конектиться по нему?
