### ISSUE TITLE
How to control or get rid of sounds

### ISSUE THREAD

**Issue by pribilinskiy** [DmitryKoterov/dklab_realsync#37]
Is there any way to suppress, mute, change volume of sounds or the sound itself?

I hear sound when a file is copied and when a popup appears

While notifications (banner and sound) can be easily controlled in Windows:
![image](https://user-images.githubusercontent.com/3078595/29446834-09e1b758-83f7-11e7-94bd-2aa48816c46c.png)
![image](https://user-images.githubusercontent.com/3078595/29446836-12e9429e-83f7-11e7-9871-c644e4336c45.png)

I don't see a way how to control the notification sound when small files are copied

**Comment by DmitryKoterov** [comment]
I suppose there is a config file option (in .realsync file) for this, no?

**Comment by pribilinskiy** [comment]
Yep, found it
