### ISSUE TITLE
Cannot lstat  Value too large for defined data type

### ISSUE THREAD

**Issue by makm** [DmitryKoterov/dklab_realsync#40]
Помогите разобраться.
Под W10 таких проблем не было.. Но в Ubunta так. причины не понимаю

[22:13:30] Running async notification watcher (to save CPU time).
Cannot lstat(/home/maxim/work/vh/project/.gitignore): Value too large for defined data type
Cannot lstat(/home/maxim/work/vh/project/application): Value too large for defined data type
Cannot lstat(/home/maxim/work/vh/project/.git): Value too large for defined data type

**Comment by makm** [comment]
решил что бага в notify  - судя по исходникам. Просто перекомпилировал nofity и все заработало.

**Comment by AlekseyLabunskiy777** [comment]
не подскажите последовательность, как решить эту проблему например в убунте 19? спасибо за ответ.

**Comment by makm** [comment]
сейчас не могу вспомнить, но вроде я описал как решить проблему с lstat
попробуйте пересобрать notify

**Comment by yaruson** [comment]
Здесь _пересобрать notify_ — это скомпилировать notify по инструкции `src/linux/BUILD` и заменить бинарник в `/opt/dklab_realsync/bin/linux/`.
