### ISSUE TITLE
"notify: Bad CPU type in executable" in new macOS Catalina

### ISSUE THREAD

**Issue by sserg82** [DmitryKoterov/dklab_realsync#43]
```
[14:47:05] Running async notification watcher (to save CPU time).
sh: /Programming/realsync/bin/darwin/notify: Bad CPU type in executable
[14:47:05] Notification daemon is terminated unexpectedly, restarting. Command was:
[14:47:05]   "/Programming/realsync/bin/darwin/notify" "."
```
MacOS Catalina
Version 10.15 (19A583)

**Comment by hempalex** [comment]
MacOS Catalina dropped support for 32-bit executables but "notify" is 32-bit
Also as I know it must be notarized by Apple
Maybe is a way to bypass notarization check but I think you have to disable GateKeeper to do so (spctl --master-disable), which may lead to security issues with your system

**Comment by hempalex** [comment]
Try recompile it, something like
> cc -framework CoreFoundation -framework CoreServices -o notify notify.c

**Comment by hempalex** [comment]
Try my homebrew formula for realsync
https://github.com/hempalex/homebrew-formula/blob/master/dklab_realsync.rb
I've investigate a bit, it seems Catalina does not need notarisation for command line tools, only for "application"

**Comment by sserg82** [comment]
> Try recompile it, something like
> 
> > cc -framework CoreFoundation -framework CoreServices -o notify notify.c

It work, thanks!
