### ISSUE TITLE
Mac OS Big Sur Apple M1

### ISSUE THREAD

**Issue by Romik231** [DmitryKoterov/dklab_realsync#45]
Hello, I've tried install realsync and got this case
`Running async notification watcher (to save CPU time).
sh: /opt/dklab_realsync/bin/darwin/notify: Bad CPU type in executable
[11:03:45] Notification daemon is terminated unexpectedly, restarting. Command was:
[11:03:45]   "/opt/dklab_realsync/bin/darwin/notify" "."
`
I found this solution 
`cc -framework CoreFoundation -framework CoreServices -o notify notify.c`
but I had next error
`ld: can't open output file for writing: notify, errno=13 for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

if I am correct, problem in arm64 processor, can you help me resolve this problem?

**Comment by hempalex** [comment]
Try my homebrew formula for RealSync

https://github.com/hempalex/homebrew-formula/blob/master/dklab_realsync.rb

you have to install xcode command line utilities first
> xcode-select --install
